### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by dphoyes** [snoack/ssh4py#10]
Thanks for the great work on this. Have you considered making it available as a package on PyPI? I'd like to add it as a dependency for my own project.

**Comment by snoack** [comment]
Sure. I already published it on PyPI: https://pypi.python.org/pypi/goto-statement

**Comment by dphoyes** [comment]
Pretty sure that's not this project...

**Comment by snoack** [comment]
Oh, right, this is `ssh4py`, I mistakenly assumed this issue was for `python-goto`, one of my other projects.

Frankly, I no longer actively develop `ssh4py`. So I recommend that you either fork it and put it on PyPI yourself, or just use the `ssh` command line utility through the `subprocess` module.

**Comment by dphoyes** [comment]
Ok, done: https://pypi.python.org/pypi/dphoyes.libssh2/0.7.2
